locals {
  default_commit_author = "Terraform Bootstrap"
  default_commit_email  = "terraform@example.com"

  self_hosted_runner_name = local.use_runner_group ? "group: ${local.resource_names.runner_group_name}" : "self-hosted"

  target_folder_name = ".github"

  environment_replacements = { for environment_key, environment_value in local.environments : "${format("%03s", environment_value.display_order)}-${environment_key}" => {
    name                                         = lower(replace(environment_key, "-", ""))
    display_name                                 = environment_value.display_name
    runner_name                                  = var.use_self_hosted_agents ? local.self_hosted_runner_name : "ubuntu-latest"
    environment_name_plan                        = "${environment_key}-plan"
    environment_name_apply                       = "${environment_key}-apply"
    dependent_environment                        = environment_value.dependent_environment
    backend_azure_storage_account_container_name = environment_key
    root_module_folder_relative_path             = "terraform/environments/${lower(replace(environment_key, "-", ""))}"
  } }

  template_folder = "${path.module}/${var.example_module_path}"
  files = { for file in fileset(local.template_folder, "**") : file => {
    name    = file
    content = file("${local.template_folder}/${file}")
  } }

  pipeline_main_replacements = {
    environments              = local.environment_replacements
    organization_name         = var.organization_name
    repository_name_templates = github_repository.template.name
    cd_template_path          = ".github/workflows/cd-template.yaml"
    ci_template_path          = ".github/workflows/ci-template.yaml"
  }

  pipeline_main_folder = "${path.module}/../workflows/main"
  pipeline_main_files = { for file in fileset(local.pipeline_main_folder, "**") : "${local.target_folder_name}/${file}" => {
    name    = file
    content = templatefile("${local.pipeline_main_folder}/${file}", local.pipeline_main_replacements)
  } }

  main_repository_files = merge(local.files, local.pipeline_main_files)

  pipeline_template_replacements = {
    environments = local.environment_replacements
  }

  pipeline_template_folder = "${path.module}/../workflows/templates"
  pipeline_template_files = { for file in fileset(local.pipeline_template_folder, "**") : "${local.target_folder_name}/${file}" => {
    name    = file
    content = file("${local.pipeline_template_folder}/${file}")
  } }
}

resource "github_repository_file" "this" {
  for_each            = local.main_repository_files
  repository          = github_repository.this.name
  file                = each.key
  content             = each.value.content
  commit_author       = local.default_commit_author
  commit_email        = local.default_commit_email
  commit_message      = "Add ${each.key} [skip ci]"
  overwrite_on_create = true
}

resource "github_repository_file" "template" {
  for_each            = local.pipeline_template_files
  repository          = github_repository.template.name
  file                = each.key
  content             = each.value.content
  commit_author       = local.default_commit_author
  commit_email        = local.default_commit_email
  commit_message      = "Add ${each.key} [skip ci]"
  overwrite_on_create = true
}

resource "github_repository_file" "main_readme" {
  repository          = github_repository.this.name
  file                = "README.md"
  commit_author       = local.default_commit_author
  commit_email        = local.default_commit_email
  commit_message      = "Add README.md [skip ci]"
  overwrite_on_create = true
  content             = <<-EOT
    # ${github_repository.this.name}

    This repository was generated by the [Azure IaC Project Factory](https://github.com/${var.organization_name}/azure-iac-project-factory) bootstrap.
    It is a starting point that can be cloned and developed further to manage your Azure infrastructure with Terraform.

    ## Structure

    ```
    terraform/
      environments/       # One root module per environment (dev, uat, prod)
        dev/
        uat/
        prod/
      modules/            # Reusable modules shared across environments
    ```

    Each environment under `terraform/environments/` is an independent Terraform root module with its own backend state.
    Variables specific to each environment are defined in `terraform.tfvars`.

    ## CI/CD

    The GitHub Actions workflows in `.github/workflows/` call reusable workflow templates hosted in the
    [${github_repository.template.name}](https://github.com/${var.organization_name}/${github_repository.template.name}) repository.
    Changes to pipeline behaviour (steps, Terraform version handling, OIDC authentication) should be made there.

    - **CI** (`ci.yaml`) — runs `terraform plan` for all environments on every pull request targeting `main`
    - **CD** (`cd.yaml`) — runs `terraform plan` then `terraform apply` for all environments on merge to `main`

    ## Getting started

    1. Clone this repository
    2. Update `terraform/environments/*/terraform.tfvars` with your environment-specific values
    3. Add any shared infrastructure to `terraform/modules/`
    4. Raise a pull request — CI will plan all environments automatically
  EOT
}

resource "github_repository_file" "template_readme" {
  repository          = github_repository.template.name
  file                = "README.md"
  commit_author       = local.default_commit_author
  commit_email        = local.default_commit_email
  commit_message      = "Add README.md [skip ci]"
  overwrite_on_create = true
  content             = <<-EOT
    # ${github_repository.template.name}

    This repository contains reusable GitHub Actions workflow templates for Terraform deployments to Azure.
    It was created by the [Azure IaC Project Factory](https://github.com/${var.organization_name}/azure-iac-project-factory) bootstrap
    and is referenced by IaC repositories in the [${var.organization_name}](https://github.com/${var.organization_name}) organisation.

    ## Contents

    | Path | Purpose |
    |------|---------|
    | `.github/workflows/ci-template.yaml` | Reusable CI workflow — runs `terraform plan` for a single environment |
    | `.github/workflows/cd-template.yaml` | Reusable CD workflow — runs `terraform plan` then `terraform apply` for a single environment |
    | `.github/actions/validate/action.yaml` | Composite action — runs `terraform init` and `terraform validate` |

    ## How it works

    Repositories that use these templates call them via the
    [workflow_call](https://docs.github.com/en/actions/sharing-automations/reusing-workflows) trigger, for example:

    ```yaml
    jobs:
      dev_plan_and_apply:
        uses: ${var.organization_name}/${github_repository.template.name}/.github/workflows/cd-template.yaml@main
        permissions:
          id-token: write
          contents: read
        with:
          root_module_folder_relative_path: 'terraform/environments/dev'
          environment_name_plan: dev-plan
          environment_name_apply: dev-apply
    ```

    Authentication to Azure uses OIDC — no secrets are stored. Each environment uses a dedicated
    user-assigned managed identity whose `AZURE_CLIENT_ID` is set as a GitHub Actions environment variable
    by the factory bootstrap.
  EOT
}
